server:
  port: 7001

springdoc:
  packages-to-exclude:
    - org.jeecg.modules.drag
    - org.jeecg.modules.online
    - org.jeecg.modules.jmreport
spring:
  application:
    name: jeecg-system
  cloud:
    nacos:
      config:
        server-addr: @config.server-addr@
        group: @config.group@
        namespace: @config.namespace@
        username: @config.username@
        password: @config.password@
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        group: @config.group@
        namespace: @config.namespace@
        username: @config.username@
        password: @config.password@
  config:
    import:
      - optional:nacos:jeecg.yaml
      - optional:nacos:jeecg-@profile.name@.yaml